/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import { CarCarousel } from "../components/CarCarousel";
import { Flex } from "@chakra-ui/react";
import { CarCatalogSection } from "../components/CarCatalogSection";
import { CarModelSection } from "../components/CarModelSection";
import { CarMakerSection } from "../components/CarMakerSection";
import { FreeWordSearch } from "../components/FreeWordSearch";
import { NewsSection } from "../components/NewsSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Testing Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

    

      <CarCarousel />

      <CarCatalogSection />

      <Flex
        justifyContent="space-around"
        flexWrap={{ base: "wrap", sm: "wrap", md: "wrap", lg: "nowrap" }}
        mt="60px"
      >
        <CarModelSection />

        <Flex
          flexDirection="column"
          w={{ base: "340px", md: "360px", lg: "600px" }}
        >
          <CarMakerSection />

          <FreeWordSearch />
        </Flex>
      </Flex>

      <NewsSection />

   

      
    </>
  );
}
