/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import { CarCarousel } from "./components/CarCarousel";
import { Header } from "./components/Header";
import { Box, Button, Flex, Heading, Text, Image } from "@chakra-ui/react";
import { CarCatalogSection } from "./components/CarCatalogSection";
import { CarModelSection } from "./components/CarModelSection";
import { CarMakerSection } from "./components/CarMakerSection";
import { FreeWordSearch } from "./components/FreeWordSearch";

export default function Home() {
  return (
    <>
      <Head>
        <title>Testing Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <Header />
      <CarCarousel />
      <Box textAlign="center">
        <Heading
          as="h2"
          size="sm"
          fontSize={{ base: "13px", md: "20px", lg: "30px" }}
        >
          オススメの新型車(仮)
        </Heading>
        <Text
          textAlign="center"
          fontSize={{ base: "0.5em", md: "8px", lg: "15px" }}
          color="gray"
        >
          説明文が入ります。ダミーテキスト
        </Text>
        <Text
          textAlign="center"
          fontSize={{ base: "0.5em", md: "8px", lg: "15px" }}
          color="gray"
        >
          ダミーテキストダミーテキストダミーテキスト
        </Text>
      </Box>
      <Flex>
        <CarCatalogSection />
      </Flex>

      <Flex
        justifyContent="space-evenly"
        flexWrap={{ base: "wrap", sm: "wrap", lg: "nowrap" }}
        mt="60px"
      >
        <CarModelSection />
        <Flex flexDirection="column">
        <CarMakerSection />
        <FreeWordSearch />
        </Flex>
      </Flex>
    </>
  );
}
